version: "3"

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    networks:
      - nm_network
  php:
    image: "php"
    build: docker/php
    volumes:
      - ./:/app
    depends_on:
      - database
    links:
      - database
    networks:
      - nm_network
    working_dir: /app
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER_DATABASE: "${DB_USERNAME}"
      MYSQL_USER_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/db/mn_database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - nm_network
networks:
  nm_network:
      driver: bridge
volumes:
  mysqldata: {}

  